on:
  push:
    branches:
      - master

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Cache Poetry
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Setup environment
        run: |
          pip install poetry
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
      - name: Build and Push
        run: poetry publish --build --username __token__ --password "$PYPI_TOKEN"
